cookie:
  expiry_days: 30
  key: b1d8e9c4-40a4-4f1a-9b7f-9e7a7a1e0b1f
  name: vietvang
credentials:
  usernames:
    admin:
      email: caoquoc110602@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: KGK
      password: $2b$12$vBZEb5mX274cnNl4YjcVo.urCzIVYeG80c.Gy1e50Wek8n0E1Lm52
    user:
      email: caoquocworkandstudy@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: KGK
      password: $2b$12$mP7p.btCxsuwhBklT4goA./JOfz2aBhlElrE.uvDz1MmzYOZ/glbu
pre-authorized:
  emails:
  - caoquoc.job@gmail.com
